# Generated by Django 4.2.5 on 2023-09-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=150, verbose_name='E-mail')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
